### ISSUE TITLE
Renaming a Class function sometimes fails and leaves a corrupt project

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#12] opened 2016-06-09 18:07 UTC
It seems there is an issue with the Class renaming menu function. It fails. I'm not sure what the conditions are to reproduce this. However when it fails, I have to revert my source from source control. Mainly because it leaves the class in a partial renamed state and deletes some VIs. So this is a dangerous failure mode. I have fear in using it again. So I cannot recommend anyone use it.

I will add more info to this issue when I have something to add.

**Comment by MikaelHolmstrom** [comment] 2016-06-09 22:10
I've not seen this before, and I've used it a lot.
Can you give me a copy of the class you try to rename?
Are you using Auto populate folders i the project where the class sits?

**Comment by Bas-vE** [comment] 2024-03-08 17:11
Closed this issue because I cannot reproduce this in the latest version

**Closed by Bas-vE** 2024-03-08 17:11 UTC
