### ISSUE TITLE
Error dialog when creating a method

### ISSUE THREAD

**Issue by MichaelAivaliotis** [opengds/OpenGDS#10] opened 2016-06-07 23:11 UTC
I got the following error message while creating a method:

```
Error 1 occurred at File/Directory Info in File_CreateFolders.vi->Scripting_SaveVi.vi->ClassWriterNative.lvclass:CreateMethod.vi->GOOP_LVClass_Item_OnCommand.vi->GOOP_LVClass_Item_OnCommand.vi.ProxyCaller

Possible reason(s):

LabVIEW:  An input parameter is invalid. For example if the input is a path, the path might contain a character not allowed by the OS such as ? or @.
=========================
NI-488:  Command requires GPIB Controller to be Controller-In-Charge.

<Not A Path><Array>
<Name>ErrorArray</Name>
<Dimsize>1</Dimsize>
<LvVariant>
<Name>VariantError</Name>
<Cluster>
<Name>ErrorLogCluster</Name>
<NumElts>6</NumElts>
<Timestamp>
<Name>Time</Name>
<Cluster>
<Name></Name>
<NumElts>4</NumElts>
<I32>
<Name></Name>
<Val>0</Val>
</I32>
<I32>
<Name></Name>
<Val>-841814016</Val>
</I32>
<I32>
<Name></Name>
<Val>-746781619</Val>
</I32>
<I32>
<Name></Name>
<Val>0</Val>
</I32>
</Cluster>
</Timestamp>
<String>
<Name></Name>
<Val>ClassWriterNative.lvclass:CreateMethod.vi</Val>
</String>
<Cluster>
<Name>error IO</Name>
<NumElts>3</NumElts>
<Boolean>
<Name>status</Name>
<Val>1</Val>
</Boolean>
<I32>
<Name>code</Name>
<Val>1</Val>
</I32>
<String>
<Name>source</Name>
<Val>File/Directory Info in File_CreateFolders.vi-&gt;Scripting_SaveVi.vi-&gt;ClassWriterNative.lvclass:CreateMethod.vi-&gt;GOOP_LVClass_Item_OnCommand.vi-&gt;GOOP_LVClass_Item_OnCommand.vi.ProxyCaller&lt;APPEND&gt;
&lt;Not A Path&gt;</Val>
</String>
</Cluster>
<String>
<Name>State</Name>
<Val>ReplaceOORefs</Val>
</String>
<String>
<Name>LocalVariabelXML</Name>
<Val>NewVIPath=&amp;lt;Not A Path&amp;gt;
TemplateName=NativeSubTemplate
DestroyProjectFolderItem=1
TemplateFolder=C:\Program Files (x86)\National Instruments\LabVIEW 2014\resource\Framework\Providers\Open_GDS\ClassProviders\Provider_LvNativeClass\Templates\NativeSubTemplate\methods
DesignPattern=0
PropertyNode=0
CommonClassTemplate=0
OnlyNormalMethod=0
OnlyPublic=0</Val>
</String>
<String>
<Name>ExtraErrorInfo</Name>
<Val></Val>
</String>
</Cluster>
</LvVariant>
</Array>
```

**Comment by MichaelAivaliotis** [comment] 2016-06-08 00:53
@MikaelHolmstrom - I have some more info on this crash.
It seems to be repeatable. It happens if I select a Project virtual sub-folder that is 2 levels deep.
If I allow it to use the project root then the error dialog doesn't happen and it proceeds as normal.

**Comment by MikaelHolmstrom** [comment] 2016-06-08 01:34
Great catch, what version are you using?

**Comment by MichaelAivaliotis** [comment] 2016-06-08 01:57
I just did a pull of the latest from Git.

**Comment by MikaelHolmstrom** [comment] 2016-06-08 02:03
If you just did a pull straight into the LabVIEW 2014 folder you'll get some issues, since that version is 2012 version. During the build process some AF VIs gets modified to work in 2013 and later.
But you should be good for the next pull :-)

**Comment by MichaelAivaliotis** [comment] 2016-06-08 02:04
I pulled into a separate folder then copied in. But that's probably the same thing I assume.

**Comment by MikaelHolmstrom** [comment] 2016-06-11 23:13
Hmm, I can't reproduce it.
Is the class saved?
You just create 2 virtual folder within each other and then try to add a method and place it in that virtual folder?!?

**Comment by Bas-vE** [comment] 2024-03-08 17:09
CLosing this because I cannot reproduce this in the latest version

**Closed** 2024-03-08 17:09 UTC
